apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcs-pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcs
  template:
    metadata:
      name: tcs
      labels:
        app: tcs
    spec:
      containers:
      - image: sammyne/hyperledger-tcf
        name: tcs
        command: ["/bin/bash"]
        args: ["$(TCF_HOME)/scripts/tcs_listener.sh"]
        env:
        - name: TCF_HOME
          value: /project/TrustedComputeFramework
---
apiVersion: v1
kind: Service
metadata:
  name: tcs
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: tcs
