# Copyright 2019 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

title = "TCF Connector configuration"

[owner]
name = "TCF"
organization = "Intel"

[tcf]
#Uri for the worker registry
json_rpc_uri = "http://localhost:1947"

#Block chain type, it identifies which blockchain to use
[blockchain]
type = "ethereum"

[ethereum]
#Direct registry contract file
direct_registry_contract_file = "sdk/avalon_sdk/ethereum/contracts/WorkerRegistryList.sol"
#Worker registry contract file
worker_registry_contract_file = "sdk/avalon_sdk/ethereum/contracts/WorkerRegistry.sol"
#Proxy worker registry contract file
proxy_worker_registry_contract_file = "sdk/avalon_sdk/ethereum/contracts/proxy-model/WorkerRegistry.sol"
#Worker registry contract file
work_order_contract_file = "sdk/avalon_sdk/ethereum/contracts/proxy-model/WorkOrderRegistry.sol"

#Initially deploy the contracts using eth_cli.py to get the these addresses
#Deployed contract address of direct registry contract address.
direct_registry_contract_address = "0xD5A613945DE851C7c2f83fFDA4de0aE01CE980c0"
#Deployed contract address of worker registry contract address.
worker_registry_contract_address = "0x523748D492AfEEC90767403Da7C1e86feBB10435"
#Deployed contract address of direct registry contract address.
proxy_worker_registry_contract_address = "0x76Cf65807D6F2E749fF1f3dAc79e6b44fc21f0f6"
#Deployed contract address of worker registry contract address.
work_order_contract_address = "0x2525fef0dE3454e05b37F040d2f4862C3460f2E6"

#Ethereum account details
eth_account = "0xefb21e451a2f8c9e25e02ffee969b169a067d343"
#Ethereum account private key 
acc_pvt_key = "4F611197A6E82715F4D2446FE015D1667E9C40A351411F3A7300F71F285D01B4"

#Version of solc to be used for compiling Solidity contracts 
solc_version = "v0.5.15"
#Provider for test network. The default url is for a Hyperledger Besu client.
#This could be replaced with a Ropsten(Infura as the IAAS) provider or a Ganache client.
provider = "http://10.66.245.80:8545"
#chain_id is 3 for ropsten test network
#"1": Ethereum Mainnet
#"2": Morden Testnet (deprecated)
#"3": Ropsten Testnet
#"4": Rinkeby Testnet
#"42": Kovan Testnet
chain_id = 3
gas_limit = 3000000
gas_price = "100"

# Fabric blockchain
[fabric]
fabric_network_file = "sdk/avalon_sdk/fabric/network.json"
channel_name = "mychannel"
